### ISSUE TITLE
Updating entity fails if the entity's `id` is 0

### ISSUE THREAD

**Issue by zachcoyle** [leoselig/redux-entitize#12]
https://github.com/leoselig/redux-entitize/blob/master/src/reducer/index.js#L73

**Comment by leoselig** [comment]
Hey @zachcoyle, tanks for your PR on this!
I added a test case for this in https://github.com/leoselig/redux-entitize/pull/14
Once it's merged, I'm releasing a `0.5.5`.

**Comment by zachcoyle** [comment]
👍 awesome!
