### ISSUE TITLE
Remove references in other entities when deleting an entity

### ISSUE THREAD

**Issue by georgberecz** [leoselig/redux-entitize#7]
It would be great if references that might still exist are removed, when using a `deleteEntityAction`.
Example:
Using `deleteEntityAction('comments', 'comment1')` does not automatically update the reference in `users` currently. That leads to problems, when trying to access such a comment in a user object.
```
entities: {
  users: {
    user1: {
      id: "user1"
      comments: ["comment1", "comment2"]
    }
  },
  comments: {
    comment1: {
      id: "comment1"
    },
    comment2: {
      id: "comment2"
    }
  }
}
```

Greetings,
Georg :)

**Comment by leoselig** [comment]
Resolved as of [`0.5.1`](https://github.com/leoselig/redux-entitize/blob/master/CHANGELOG.md#version-051) with [PR #9](https://github.com/leoselig/redux-entitize/pull/9)
